const state={theme:"consumption",metric:"total",year:2024,selected:null,data:{}};
const configs={
 consumption:{question:"Où l’énergie est-elle consommée ?",intro:"Compare les communes, les filières et les secteurs d’activité.",source:"Agence ORE · gestionnaires de réseaux d’électricité et de gaz",link:"https://opendata.agenceore.fr/explore/dataset/consommation-annuelle-d-electricite-et-gaz-par-commune/",method:"Données 2020–2024. Les consommations secrétisées ne sont pas reconstituées.",layers:[
  ["total","Consommation totale","Électricité + gaz · MWh","#000091"],["residentiel","Secteur résidentiel","Consommation des logements","#6a6af4"],["tertiaire","Secteur tertiaire","Commerces, bureaux et services","#009081"],["industrie","Industrie","Activités industrielles","#e1000f"],["evolution","Évolution depuis 2020","Variation en pourcentage","#ce614a"]]},
 production:{question:"Où produit-on de l’énergie ?",intro:"Localise les installations renouvelables en service et compare les puissances.",source:"ODRÉ · RTE · Enedis · registre national des installations",link:"https://odre.opendatasoft.com/explore/dataset/registre-national-installation-production-stockage-electricite-agrege/",method:"Le registre détaille les installations publiables. Les petites installations peuvent être agrégées ou protégées.",layers:[
  ["power","Puissance installée","Toutes les filières · kW","#18753c"],["solar","Solaire photovoltaïque","Puissance des installations","#ffca00"],["bio","Bioénergies","Biogaz, biomasse, déchets","#6a4c93"],["count","Nombre d’installations","Installations recensées","#009081"]]},
 renovation:{question:"Où concentrer la rénovation ?",intro:"Observe la performance énergétique des logements diagnostiqués depuis juillet 2021.",source:"ADEME · Observatoire DPE-Audit",link:"https://www.data.gouv.fr/dataservices/dpe-logements-existants-depuis-juillet-2021",method:"Les DPE enregistrés ne couvrent pas tout le parc et ne sont pas un échantillon statistiquement représentatif.",layers:[
  ["passoires","Passoires thermiques","Part des classes F et G","#e1000f"],["efg","Logements classés E à G","Rénovations à anticiper","#ce614a"],["performants","Logements performants","Part des classes A et B","#18753c"],["coverage","DPE enregistrés","Nombre de diagnostics valides","#000091"]]},
 air:{question:"Quelle qualité de l’air respirons-nous ?",intro:"Affiche les concentrations modélisées par Airparif et les principaux polluants réglementés.",source:"Airparif · réseau francilien de surveillance",link:"https://www.airparif.fr/surveiller-la-pollution/la-pollution-en-direct-en-ile-de-france",method:"Une concentration représente le niveau respiré ; elle ne doit pas être confondue avec les émissions à la source.",layers:[
  ["no2","Dioxyde d’azote · NO₂","Concentration annuelle modélisée","#7a1f5c"],["pm10","Particules · PM10","Concentration annuelle modélisée","#ce614a"],["pm25","Particules fines · PM2,5","Indicateur sanitaire","#e4794a"],["atmo","Indice ATMO","Information quotidienne Airparif","#000091"]]}
};

const map=L.map("map",{zoomControl:false,minZoom:8,maxZoom:18}).setView([49.07,2.1],10);L.control.zoom({position:"bottomright"}).addTo(map);
L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap",maxZoom:19}).addTo(map);
let communeLayer,airLayer;

Promise.all([
 fetch("data/communes.geojson").then(r=>r.json()),fetch("data/consommation.json").then(r=>r.json()),fetch("data/production.json").then(r=>r.json()),fetch("data/dpe.json").then(r=>r.json()),fetch("data/meta.json").then(r=>r.json())
]).then(([communes,consumption,production,dpe,meta])=>{
 state.data={communes,consumption,production,dpe,meta};prepare();
 document.querySelector("#freshness").textContent=`Synchronisation ${new Date(meta.generated).toLocaleDateString("fr-FR")} · ${meta.communeCount} communes`;
 communeLayer=L.geoJSON(communes,{style:feature=>styleFeature(feature),onEachFeature:(feature,layer)=>{layer.on({click:()=>selectCommune(feature),mouseover:e=>e.target.setStyle({weight:2,color:"#000091"}),mouseout:e=>communeLayer.resetStyle(e.target)});layer.bindTooltip(feature.properties.nom,{sticky:true});}}).addTo(map);
 map.fitBounds(communeLayer.getBounds(),{padding:[20,20]});render();buildDashboard();
}).catch(error=>{document.querySelector("#freshness").textContent="Données indisponibles";console.error(error)});

function prepare(){
 const d=state.data;d.commune={};d.communes.features.forEach(f=>d.commune[f.properties.code]={name:f.properties.nom,pop:f.properties.population||0,cons:{},prod:{power:0,count:0,solar:0,bio:0},dpe:null});
 d.consumption.forEach(r=>{const c=d.commune[r.code_commune];if(!c)return;const year=+r.annee;const sector=(r.code_grand_secteur||"inconnu").toLowerCase();c.cons[year]||={total:0,residentiel:0,tertiaire:0,industrie:0,agriculture:0,electricite:0,gaz:0};c.cons[year].total+=r.conso_mwh||0;c.cons[year][sector]=(c.cons[year][sector]||0)+(r.conso_mwh||0);c.cons[year][r.filiere.toLowerCase().startsWith("elec")?"electricite":"gaz"]+=r.conso_mwh||0;});
 d.production.forEach(r=>{const c=d.commune[r.code];if(!c)return;c.prod.power+=r.puissance_kw||0;c.prod.count+=r.installations||1;if((r.filiere||"").includes("Solaire"))c.prod.solar+=r.puissance_kw||0;if(/Bio|Thermique/.test(r.filiere||""))c.prod.bio+=r.puissance_kw||0;});
 d.dpe.forEach(r=>{if(d.commune[r.code])d.commune[r.code].dpe=r});
}
function metric(code){const c=state.data.commune?.[code];if(!c)return 0;if(state.theme==="consumption"){const a=c.cons[state.year]||{};if(state.metric==="evolution"){const b=c.cons[2020]?.total||0;return b?((a.total-b)/b*100):0}return a[state.metric]||0}if(state.theme==="production")return c.prod[state.metric]||0;if(state.theme==="renovation"){const x=c.dpe;if(!x)return 0;if(state.metric==="coverage")return x.total;const sum=k=>k.reduce((n,l)=>n+(x.classes[l]||0),0);if(state.metric==="passoires")return 100*sum(["F","G"])/x.total;if(state.metric==="efg")return 100*sum(["E","F","G"])/x.total;return 100*sum(["A","B"])/x.total}return 0}
function values(){return Object.keys(state.data.commune||{}).map(metric).filter(Number.isFinite).sort((a,b)=>a-b)}
function color(v){const vals=values(),max=vals[Math.floor(vals.length*.95)]||1;if(state.theme==="air")return "#e3e3fd";const t=Math.max(0,Math.min(1,v/max));const colors=state.theme==="production"?["#dffee8","#18753c"]:state.theme==="renovation"&&state.metric==="performants"?["#dffee8","#18753c"]:["#e3e3fd","#000091"];return mix(colors[0],colors[1],t)}
function mix(a,b,t){const x=n=>parseInt(n,16),ar=x(a.slice(1,3)),ag=x(a.slice(3,5)),ab=x(a.slice(5,7)),br=x(b.slice(1,3)),bg=x(b.slice(3,5)),bb=x(b.slice(5,7));return`rgb(${Math.round(ar+(br-ar)*t)},${Math.round(ag+(bg-ag)*t)},${Math.round(ab+(bb-ab)*t)})`}
function styleFeature(f){return{color:"#777",weight:.7,fillColor:color(metric(f.properties.code)),fillOpacity:.78}}
function render(){const cfg=configs[state.theme];document.querySelector("#question").textContent=cfg.question;document.querySelector("#intro").textContent=cfg.intro;document.querySelector("#sourceText").textContent=cfg.source;document.querySelector("#sourceLink").href=cfg.link;document.querySelector("#methodText").textContent=cfg.method;document.querySelector("#layers").innerHTML=cfg.layers.map(([id,label,detail,c])=>`<button class="layer ${id===state.metric?"active":""}" data-metric="${id}"><i style="--color:${c}"></i><span><b>${label}</b><small>${detail}</small></span><em></em></button>`).join("");document.querySelectorAll(".layer").forEach(b=>b.onclick=()=>{state.metric=b.dataset.metric;refreshMap();render()});document.querySelector("#legendTitle").textContent=cfg.layers.find(x=>x[0]===state.metric)?.[1]||"Indicateur";renderStats();if(state.theme==="air")showAir();else hideAir()}
function refreshMap(){communeLayer?.setStyle(f=>styleFeature(f));if(state.selected)showDrawer(state.selected)}
function renderStats(){const vals=values(),sum=vals.reduce((a,b)=>a+b,0),cfg={consumption:[[fmt(sum),"MWh cumulés"],[fmt(sum/(state.data.meta?.communeCount||1)),"MWh / commune"]],production:[[fmt(sum),"kW installés"],[fmt(Object.values(state.data.commune||{}).reduce((n,c)=>n+c.prod.count,0)),"installations"]],renovation:[[fmt(state.data.meta?.dpeRows||0),"DPE analysés"],[fmt(vals.reduce((a,b)=>a+b,0)/(vals.length||1),1)+" %","moyenne communale"]],air:[["NO₂ · PM10","polluants cartographiés"],["Airparif","données de référence"]]}[state.theme];document.querySelector("#stats").innerHTML=cfg.map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("")}
function selectCommune(f){state.selected=f.properties.code;showDrawer(state.selected);map.fitBounds(L.geoJSON(f).getBounds(),{padding:[60,60],maxZoom:13})}
function showDrawer(code){const c=state.data.commune[code],cons=c.cons[2024]||{},dpe=c.dpe,prod=c.prod;let detail="";if(state.theme==="consumption")detail=`<div class="hero-number"><b>${fmt(cons.total||0)} MWh</b><span>consommation électrique et gazière en 2024</span></div>${bars([["Résidentiel",cons.residentiel],["Tertiaire",cons.tertiaire],["Industrie",cons.industrie],["Agriculture",cons.agriculture]],cons.total)}`;if(state.theme==="production")detail=`<div class="hero-number"><b>${fmt(prod.power)} kW</b><span>puissance publiée en service</span></div>${bars([["Solaire",prod.solar],["Bioénergies",prod.bio],["Autres filières",Math.max(0,prod.power-prod.solar-prod.bio)]],prod.power)}<p class="note">${fmt(prod.count)} installation(s) recensée(s).</p>`;if(state.theme==="renovation")detail=dpe?`<div class="hero-number"><b>${pct((dpe.classes.F+dpe.classes.G)/dpe.total)}</b><span>de diagnostics classés F ou G</span></div>${dpeChart(dpe)}<p class="note">${fmt(dpe.total)} DPE valides depuis juillet 2021. Cette distribution ne représente pas nécessairement l’ensemble du parc.</p>`:`<p>Aucun agrégat DPE exploitable.</p>`;if(state.theme==="air")detail=`<div class="hero-number"><b>Airparif</b><span>cartographie régionale des concentrations</span></div><p>Active le polluant souhaité puis zoome sur la commune. Les couches modélisées complètent les mesures des stations.</p>`;document.querySelector("#drawerContent").innerHTML=`<p class="kicker">FICHE COMMUNALE</p><span class="code">${code} · ${fmt(c.pop)} habitants</span><h2>${c.name}</h2>${detail}`;document.querySelector("#drawer").classList.add("open")}
function bars(items,total){return`<div class="bars">${items.filter(x=>x[1]).map(([l,v])=>`<div class="bar"><span>${l}</span><div class="track"><i style="width:${Math.min(100,100*v/(total||1))}%"></i></div><b>${fmt(v)}</b></div>`).join("")}</div>`}
function dpeChart(d){const colors={A:"#319834",B:"#56ae35",C:"#c8d300",D:"#f4e70f",E:"#f0b50f",F:"#e97720",G:"#d7221f"};return`<div class="dpe-grid">${Object.entries(d.classes).map(([k,v])=>`<span style="background:${colors[k]}" title="${v} DPE">${k}<small>${Math.round(100*v/d.total)}%</small></span>`).join("")}</div>`}
function showAir(){if(airLayer)map.removeLayer(airLayer);const layerName={no2:"NO2",pm10:"PM10",pm25:"PM25",atmo:"NO2"}[state.metric];airLayer=L.tileLayer.wms("https://magellan.airparif.asso.fr/geoserver/hor_AIR/wms",{layers:layerName,format:"image/png",transparent:true,opacity:.58,attribution:"Airparif"}).addTo(map)}function hideAir(){if(airLayer){map.removeLayer(airLayer);airLayer=null}}
function buildDashboard(){const c=state.data.commune,latest=Object.values(c).reduce((s,x)=>s+(x.cons[2024]?.total||0),0),prev=Object.values(c).reduce((s,x)=>s+(x.cons[2020]?.total||0),0),power=Object.values(c).reduce((s,x)=>s+x.prod.power,0),pass=state.data.dpe.reduce((s,x)=>s+x.classes.F+x.classes.G,0),dpe=state.data.dpe.reduce((s,x)=>s+x.total,0);const years=[2020,2021,2022,2023,2024],series=years.map(y=>Object.values(c).reduce((s,x)=>s+(x.cons[y]?.total||0),0)),max=Math.max(...series);document.querySelector("#dashboardContent").innerHTML=`<div class="dash-grid"><article class="dash-card"><b>${fmt(latest/1e6,2)} TWh</b><span>consommation électricité + gaz en 2024</span></article><article class="dash-card"><b>${pct((latest-prev)/prev,true)}</b><span>évolution depuis 2020</span></article><article class="dash-card"><b>${fmt(power/1000,1)} MW</b><span>puissance de production publiée</span></article><article class="dash-card"><b>${pct(pass/dpe)}</b><span>de DPE classés F ou G</span></article><article class="dash-card dash-wide"><h3>Évolution de la consommation</h3><div class="chart">${series.map((v,i)=>`<div style="height:${100*v/max}%" title="${fmt(v)} MWh"><small>${years[i]}</small></div>`).join("")}</div></article><article class="dash-card dash-wide"><h3>Couverture des données</h3><p>${fmt(state.data.meta.consumptionRows)} agrégats énergie · ${fmt(state.data.meta.productionRows)} installations · ${fmt(state.data.meta.dpeRows)} diagnostics traités · ${state.data.meta.communeCount} communes.</p><p class="note">Les indicateurs conservent les limites et règles de secret statistique de chaque producteur.</p></article></div>`}
function fmt(v,d=0){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:d}).format(v||0)}function pct(v,signed=false){return`${signed&&v>0?"+":""}${fmt(v*100,1)} %`}

document.querySelectorAll(".tabs button[data-theme]").forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;state.metric=configs[state.theme].layers[0][0];document.querySelectorAll(".tabs button").forEach(x=>x.classList.toggle("active",x===b));refreshMap();render()});document.querySelector("#close").onclick=()=>document.querySelector("#drawer").classList.remove("open");document.querySelector("#home").onclick=()=>communeLayer&&map.fitBounds(communeLayer.getBounds(),{padding:[20,20]});document.querySelector("[data-view=dashboard]").onclick=()=>document.querySelector("#dashboard").hidden=false;document.querySelector("#closeDashboard").onclick=()=>document.querySelector("#dashboard").hidden=true;
document.querySelector("#query").oninput=e=>{const q=e.target.value.toLowerCase().trim(),box=document.querySelector("#suggestions");if(q.length<2){box.innerHTML="";return}const matches=Object.entries(state.data.commune||{}).filter(([,c])=>c.name.toLowerCase().includes(q)).slice(0,7);box.innerHTML=matches.map(([code,c])=>`<button data-code="${code}">${c.name}</button>`).join("");box.querySelectorAll("button").forEach(b=>b.onclick=()=>{const f=state.data.communes.features.find(x=>x.properties.code===b.dataset.code);selectCommune(f);document.querySelector("#query").value=f.properties.nom;box.innerHTML=""})};document.querySelector("#search").onsubmit=e=>{e.preventDefault();document.querySelector("#suggestions button")?.click()};
