const BOUNDS_95=[[48.88,1.60],[49.25,2.62]];
const state={data:{},communes:null,territory:null,mask:null,layers:{},charts:[],basemap:"plan",active:null};
const layers=[
 {id:"conso-total",group:"Consommation",title:"Consommation totale",detail:"Électricité + gaz · 2024",color:"#000091",kind:"choropleth",metric:"consoTotal",unit:"MWh",active:true},
 {id:"electricite",group:"Consommation",title:"Consommation d’électricité",detail:"Tous secteurs · 2024",color:"#0063cb",kind:"choropleth",metric:"electricite",unit:"MWh"},
 {id:"gaz",group:"Consommation",title:"Consommation de gaz",detail:"Tous secteurs · 2024",color:"#e4794a",kind:"choropleth",metric:"gaz",unit:"MWh"},
 {id:"conso-hab",group:"Consommation",title:"Consommation par habitant",detail:"Électricité + gaz · 2024",color:"#6a6af4",kind:"choropleth",metric:"consoHab",unit:"MWh/hab."},
 {id:"residentiel",group:"Consommation",title:"Secteur résidentiel",detail:"Logements · 2024",color:"#009081",kind:"choropleth",metric:"residentiel",unit:"MWh"},
 {id:"tertiaire",group:"Consommation",title:"Secteur tertiaire",detail:"Bureaux, commerces, services",color:"#00a7b5",kind:"choropleth",metric:"tertiaire",unit:"MWh"},
 {id:"industrie",group:"Consommation",title:"Secteur industriel",detail:"Activités industrielles",color:"#e1000f",kind:"choropleth",metric:"industrie",unit:"MWh"},
 {id:"production",group:"Production locale",title:"Puissance installée",detail:"Installations en service · ODRÉ",color:"#18753c",kind:"choropleth",metric:"power",unit:"kW"},
 {id:"solaire",group:"Production locale",title:"Solaire photovoltaïque",detail:"Puissance publiée",color:"#f2b705",kind:"points",metric:"solar",unit:"kW"},
 {id:"installations",group:"Production locale",title:"Installations en service",detail:"Registre national",color:"#6a4c93",kind:"points",metric:"count",unit:"installation(s)"},
 {id:"passoires",group:"Rénovation énergétique",title:"Passoires énergétiques",detail:"DPE classés F ou G",color:"#e1000f",kind:"choropleth",metric:"passoires",unit:"%"},
 {id:"efg",group:"Rénovation énergétique",title:"Logements classés E à G",detail:"DPE enregistrés depuis 2021",color:"#e4794a",kind:"choropleth",metric:"efg",unit:"%"},
 {id:"performants",group:"Rénovation énergétique",title:"Logements performants",detail:"DPE classés A ou B",color:"#18753c",kind:"choropleth",metric:"performants",unit:"%"}
];
const sources=[
 {title:"Consommation annuelle d’électricité et de gaz par commune",producer:"Agence ORE",date:"2020–2024",url:"https://opendata.agenceore.fr/explore/dataset/consommation-annuelle-d-electricite-et-gaz-par-commune/",text:"Consommations par commune, filière et grand secteur."},
 {title:"Registre national des installations de production",producer:"ODRÉ · RTE · Enedis",date:"mai 2026",url:"https://odre.opendatasoft.com/explore/dataset/registre-national-installation-production-stockage-electricite-agrege/",text:"Installations en service et puissances publiables."},
 {title:"DPE des logements existants",producer:"ADEME",date:"depuis juillet 2021",url:"https://www.data.gouv.fr/dataservices/dpe-logements-existants-depuis-juillet-2021",text:"Diagnostics agrégés par commune ; aucune adresse publiée."},
 {title:"Découpage administratif",producer:"Etalab",date:"COG 2026",url:"https://geo.api.gouv.fr/decoupage-administratif/communes",text:"Contours, codes et populations communales."}
];

function prepareEnergy(){Object.values(state.data.byCommune).forEach(c=>{const y=c.cons[2024]||{};y.electricite=0;y.gaz=0;c.electricite=0;c.gaz=0});state.data.consumption.filter(r=>Number(r.annee)===2024).forEach(r=>{const c=state.data.byCommune[r.code_commune];if(!c)return;const key=String(r.filiere).toLowerCase().startsWith("elec")?"electricite":"gaz";c[key]+=r.conso_mwh||0;c.cons[2024][key]+=r.conso_mwh||0})}
function extraCommuneDetails(code){const c=state.data.byCommune[code],current=c.cons[2024]||{},old=c.cons[2020]||{},sectors=[["Résidentiel",current.residentiel||0],["Tertiaire",current.tertiaire||0],["Industrie",current.industrie||0],["Agriculture",current.agriculture||0]],max=Math.max(1,...sectors.map(x=>x[1])),evolution=old.total?100*(current.total-old.total)/old.total:null,producers=(state.data.production||[]).filter(p=>p.code===code).sort((a,b)=>b.puissance_kw-a.puissance_kw);return`<section class="detail-subsection"><h3>Consommation par secteur</h3>${sectors.map(([label,value])=>`<div class="sector-row"><span>${label}</span><span class="sector-track"><i style="width:${100*value/max}%"></i></span><b>${fmt(value)} MWh</b></div>`).join("")}${evolution!==null?`<p><span class="evolution-badge">${evolution>0?"+":""}${fmt(evolution,1)} % depuis 2020</span></p>`:""}</section><section class="detail-subsection"><h3>Installations de production publiées</h3><p>${producers.length?`${producers.length} installation(s) détaillée(s) dans le registre national.`:"Aucune installation détaillée publiée pour cette commune."}</p><div class="producer-list">${producers.map((p,i)=>`<article class="producer-card"><header><h4>${p.nom&&p.nom!=="Confidentiel"?esc(p.nom):`${esc(p.filiere||"Production")} · installation ${i+1}`}</h4><strong>${fmt(p.puissance_kw,1)} kW</strong></header><span>${esc(p.technologie||p.filiere||"Technologie non renseignée")}</span><div class="producer-meta"><div><small>Mise en service</small><b>${p.mise_en_service?new Date(p.mise_en_service).toLocaleDateString("fr-FR"):"Non renseignée"}</b></div><div><small>Gestionnaire</small><b>${esc(p.gestionnaire||"Non renseigné")}</b></div><div><small>Injection annuelle</small><b>${p.injection_kwh?`${fmt(p.injection_kwh)} kWh`:"Non publiée"}</b></div><div><small>Raccordement</small><b>${esc([p.tension,p.raccordement].filter(Boolean).join(" · ")||"Non renseigné")}</b></div>${p.poste_source?`<div><small>Poste source</small><b>${esc(p.poste_source)}</b></div>`:""}<div><small>Source</small><b>ODRÉ · RTE · Enedis</b></div></div></article>`).join("")}</div></section>`}
const openCommuneBase=openCommune;openCommune=function(code){openCommuneBase(code);const content=document.getElementById("detailContent"),sourceButton=content.querySelector(".source-link");sourceButton?.insertAdjacentHTML("beforebegin",extraCommuneDetails(code))};
function openProductionSite(site,index,total){const title=site.nom&&site.nom!=="Confidentiel"?esc(site.nom):`${esc(site.filiere||"Production")} · installation ${index+1}`,injection=site.injection_kwh?`${fmt(site.injection_kwh)} kWh`:"Non publiée";document.getElementById("detailContent").innerHTML=`<span class="detail-tag">SITE DE PRODUCTION · ${esc(site.code)}</span><h2>${title}</h2><p class="subtitle">${esc(site.commune)} · installation ${index+1} sur ${total} publiée(s) dans la commune</p><div class="hero-production"><small>PUISSANCE INSTALLÉE</small><strong>${fmt(site.puissance_kw,1)} kW</strong><span>${esc(site.technologie||site.filiere||"Technologie non renseignée")}</span></div><div class="property-grid"><div class="property"><small>Filière</small><strong>${esc(site.filiere||"Non renseignée")}</strong></div><div class="property"><small>Mise en service</small><strong>${site.mise_en_service?new Date(site.mise_en_service).toLocaleDateString("fr-FR"):"Non renseignée"}</strong></div><div class="property"><small>Gestionnaire</small><strong>${esc(site.gestionnaire||"Non renseigné")}</strong></div><div class="property"><small>Injection annuelle</small><strong>${injection}</strong></div><div class="property"><small>Tension</small><strong>${esc(site.tension||"Non renseignée")}</strong></div><div class="property"><small>Raccordement</small><strong>${esc(site.raccordement||"Non renseigné")}</strong></div>${site.poste_source?`<div class="property"><small>Poste source</small><strong>${esc(site.poste_source)}</strong></div>`:""}<div class="property"><small>Source</small><strong>ODRÉ · RTE · Enedis</strong></div></div><p class="water-reading-note">Le registre localise l’installation à la commune. Le point cartographique est indicatif et ne représente pas une adresse précise.</p><button class="source-link" onclick="document.getElementById('sourcesDialog').showModal()">Voir la source et les précautions</button>`;document.getElementById("detailPanel").classList.add("open")}
function productionPointLayer(source){const sites=(state.data.production||[]).filter(p=>source.id!=="solaire"||String(p.filiere).includes("Solaire")),byCode={};sites.forEach(p=>(byCode[p.code]||=[]).push(p));const group=L.layerGroup(),max=Math.max(1,...sites.map(p=>p.puissance_kw||0));Object.entries(byCode).forEach(([code,items])=>{const feature=state.data.communes.features.find(f=>f.properties.code===code);if(!feature)return;const center=L.geoJSON(feature).getBounds().getCenter();items.forEach((site,index)=>{const angle=index*2.399963,size=Math.min(.012,.0035*Math.sqrt(items.length)),lat=center.lat+Math.sin(angle)*size,lng=center.lng+Math.cos(angle)*size,marker=L.circleMarker([lat,lng],{radius:Math.max(5,Math.min(16,5+11*Math.sqrt((site.puissance_kw||0)/max))),color:"#fff",weight:2,fillColor:source.color,fillOpacity:.9});marker.bindTooltip(`${site.commune} · ${site.technologie||site.filiere} · ${fmt(site.puissance_kw,1)} kW`,{sticky:true});marker.on("click",()=>openProductionSite(site,index,items.length));marker.addTo(group)})});return group}
const createLayerBase=createLayer;createLayer=function(source){return source.kind==="points"?productionPointLayer(source):createLayerBase(source)};
const map=L.map("map",{zoomControl:false,attributionControl:true,minZoom:7,maxZoom:19,zoomSnap:.25}).fitBounds(BOUNDS_95);
map.createPane("maskPane");map.getPane("maskPane").style.zIndex=420;map.createPane("boundaryPane");map.getPane("boundaryPane").style.zIndex=430;
const baseLayers={plan:L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,className:"neutral-tiles",attribution:"© contributeurs OpenStreetMap"}),ortho:L.tileLayer("https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image/jpeg",{maxZoom:19,attribution:"Photographies aériennes · IGN"})};baseLayers.plan.addTo(map);L.control.zoom({position:"bottomright"}).addTo(map);

function fmt(v,d=0){return new Intl.NumberFormat("fr-FR",{maximumFractionDigits:d}).format(Number(v)||0)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function mix(a,b,t){const p=x=>parseInt(x,16),u=(x,y)=>Math.round(x+(y-x)*t);return`rgb(${u(p(a.slice(1,3)),p(b.slice(1,3)))},${u(p(a.slice(3,5)),p(b.slice(3,5)))},${u(p(a.slice(5,7)),p(b.slice(5,7)))})`}
function metric(code,id=state.active){const c=state.data.byCommune?.[code],l=layers.find(x=>x.id===id);if(!c||!l)return 0;return Number(c[l.metric])||0}
function palette(layer,value,max){if(layer.kind==="air")return ["#cfd8df","#50f0e6","#50ccaa","#f0e641","#ff5050","#960032","#7d2181"][Math.max(0,Math.min(6,Math.round(value)))]||"#cfd8df";const start=layer.id==="performants"?"#e1f5e7":"#eef0ff";return mix(start,layer.color,Math.min(1,value/(max||1)))}
function prepare(){const d=state.data;d.byCommune={};d.communes.features.forEach(f=>d.byCommune[f.properties.code]={code:f.properties.code,name:f.properties.nom,pop:f.properties.population||0,cons:{},consoTotal:0,consoHab:0,residentiel:0,tertiaire:0,industrie:0,power:0,solar:0,count:0,passoires:0,efg:0,performants:0,dpe:null});d.consumption.forEach(r=>{const c=d.byCommune[r.code_commune];if(!c)return;const y=+r.annee,s=String(r.code_grand_secteur||"").toLowerCase();c.cons[y]||={total:0,residentiel:0,tertiaire:0,industrie:0,agriculture:0,electricite:0,gaz:0};c.cons[y].total+=r.conso_mwh||0;c.cons[y][s]=(c.cons[y][s]||0)+(r.conso_mwh||0);c.cons[y][String(r.filiere).startsWith("Élec")?"electricite":"gaz"]+=r.conso_mwh||0});Object.values(d.byCommune).forEach(c=>{const y=c.cons[2024]||{};c.consoTotal=y.total||0;c.consoHab=c.pop?c.consoTotal/c.pop:0;c.residentiel=y.residentiel||0;c.tertiaire=y.tertiaire||0;c.industrie=y.industrie||0});d.production.forEach(r=>{const c=d.byCommune[r.code];if(!c)return;c.power+=r.puissance_kw||0;c.count+=r.installations||1;if(String(r.filiere).includes("Solaire"))c.solar+=r.puissance_kw||0});d.dpe.forEach(x=>{const c=d.byCommune[x.code];if(!c)return;c.dpe=x;const sum=letters=>letters.reduce((n,k)=>n+(x.classes[k]||0),0);c.passoires=100*sum(["F","G"])/x.total;c.efg=100*sum(["E","F","G"])/x.total;c.performants=100*sum(["A","B"])/x.total})}
function territoryMask(data){const holes=[];data.features.forEach(f=>{const g=f.geometry;if(g.type==="Polygon")holes.push(g.coordinates[0]);else if(g.type==="MultiPolygon")g.coordinates.forEach(p=>holes.push(p[0]))});state.mask=L.geoJSON({type:"Feature",properties:{},geometry:{type:"Polygon",coordinates:[[[ -180,-85],[180,-85],[180,85],[-180,85],[-180,-85]],...holes]}},{pane:"maskPane",interactive:false,className:"map-mask",style:{stroke:false,fillColor:"#e7ebf2",fillOpacity:.94,fillRule:"evenodd"}}).addTo(map);state.territory=L.geoJSON(data,{pane:"boundaryPane",interactive:false,style:{color:"#565b6c",weight:.7,opacity:.68,fillOpacity:0}}).addTo(map);map.fitBounds(state.territory.getBounds(),{padding:[38,38]})}
function createLayer(source){const values=state.data.communes.features.map(f=>metric(f.properties.code,source.id)).sort((a,b)=>a-b),max=values[Math.floor(values.length*.95)]||1;if(source.kind==="points"){const group=L.layerGroup();state.data.communes.features.forEach(f=>{const v=metric(f.properties.code,source.id);if(!v)return;const ll=L.geoJSON(f).getBounds().getCenter();L.circleMarker(ll,{radius:Math.max(4,Math.min(18,4+14*Math.sqrt(v/max))),color:"#fff",weight:2,fillColor:source.color,fillOpacity:.85}).bindTooltip(`${f.properties.nom} · ${fmt(v)} ${source.unit}`,{sticky:true}).on("click",()=>openCommune(f.properties.code)).addTo(group)});return group}return L.geoJSON(state.data.communes,{style:f=>{const v=metric(f.properties.code,source.id);return{color:"#fff",weight:.8,fillColor:v?palette(source,v,max):"#cfd8df",fillOpacity:.83}},onEachFeature:(f,l)=>{l.bindTooltip(`${f.properties.nom} · ${fmt(metric(f.properties.code,source.id),source.unit==="%"?1:0)} ${source.unit}`,{sticky:true});l.on("click",()=>openCommune(f.properties.code))}})}
function renderLayers(){const groups=[...new Set(layers.map(s=>s.group))],root=document.getElementById("layerList");root.innerHTML=groups.map(g=>`<section class="layer-group"><div class="group-title">${g}</div>${layers.filter(s=>s.group===g).map(s=>`<label class="layer-row" style="--layer-color:${s.color}"><input id="layer-${s.id}" type="checkbox" ${s.active?"checked":""}><span class="layer-label"><strong>${s.title}</strong><small>${s.detail}</small></span><span class="legend-swatch ${s.kind==="points"?"point":""}" style="background:${s.color}"></span></label>`).join("")}</section>`).join("");layers.forEach(s=>document.getElementById(`layer-${s.id}`).onchange=e=>setLayer(s,e.target.checked))}
function clearActive(except){layers.forEach(s=>{if(s.id===except)return;const input=document.getElementById(`layer-${s.id}`);if(input?.checked){input.checked=false;if(state.layers[s.id])map.removeLayer(state.layers[s.id])}})}
function setLayer(source,on){if(source.kind==="external"){document.getElementById(`layer-${source.id}`).checked=false;window.open(sources[3].url,"_blank","noopener");return}if(on){clearActive(source.id);state.active=source.id;state.layers[source.id]||=createLayer(source);state.layers[source.id].addTo(map);renderLegend(source);document.getElementById("mapStatus").textContent=`${source.title} affichée · ${source.detail}`}else{if(state.layers[source.id])map.removeLayer(state.layers[source.id]);state.active=null;renderEmptyLegend();document.getElementById("mapStatus").textContent="Couche retirée de la carte"}}
function renderLegend(source){const vals=state.data.communes.features.map(f=>metric(f.properties.code,source.id)).sort((a,b)=>a-b),max=vals[Math.floor(vals.length*.95)]||1,el=document.getElementById("mapLegend");if(source.kind==="points")el.innerHTML=`<strong>${source.title}</strong><span><i style="background:${source.color};border-radius:50%"></i>Un cercle = une installation publiée</span><span>La taille représente la puissance installée</span>`;else el.innerHTML=`<strong>${source.title}</strong><span><i style="background:#eef0ff"></i>Valeur faible</span><span><i style="background:${source.color}"></i>Valeur élevée</span><span>95e percentile : ${fmt(max,source.unit==="%"?1:0)} ${source.unit}</span>`}
function renderEmptyLegend(){document.getElementById("mapLegend").innerHTML="<strong>Lecture de la carte</strong><span>Activez une couche pour afficher sa légende.</span>"}
function dpeBars(d){if(!d)return"<p class=\"snapshot-notice\">Aucun agrégat DPE exploitable pour cette commune.</p>";const colors={A:"#319834",B:"#56ae35",C:"#c8d300",D:"#f4e70f",E:"#f0b50f",F:"#e97720",G:"#d7221f"};return`<h3 class="detail-section-title">Étiquettes DPE enregistrées</h3><div class="property-grid">${Object.entries(d.classes).map(([k,v])=>`<div class="property" style="border-color:${colors[k]}"><small>Classe ${k}</small><strong>${fmt(100*v/d.total,1)} %</strong></div>`).join("")}</div><p class="water-reading-note">${fmt(d.total)} diagnostics valides. Cette distribution ne représente pas nécessairement l’ensemble du parc de logements.</p>`}
function openCommune(code){const c=state.data.byCommune[code],y=c.cons[2024]||{};document.getElementById("detailContent").innerHTML=`<span class="detail-tag">FICHE COMMUNALE · ${code}</span><h2>${esc(c.name)}</h2><p class="subtitle">${fmt(c.pop)} habitants · données publiques consolidées</p><div class="property-grid"><div class="property"><small>Consommation 2024</small><strong>${fmt(c.consoTotal)} MWh</strong></div><div class="property"><small>Par habitant</small><strong>${fmt(c.consoHab,1)} MWh</strong></div><div class="property"><small>Électricité</small><strong>${fmt(y.electricite)} MWh</strong></div><div class="property"><small>Gaz</small><strong>${fmt(y.gaz)} MWh</strong></div><div class="property"><small>Production publiée</small><strong>${fmt(c.power)} kW</strong></div><div class="property"><small>Installations</small><strong>${fmt(c.count)}</strong></div></div>${dpeBars(c.dpe)}<button class="source-link" onclick="document.getElementById('sourcesDialog').showModal()">Voir les sources et précautions</button>`;document.getElementById("detailPanel").classList.add("open")}
function renderSources(){document.getElementById("sourceCards").innerHTML=sources.map(s=>`<article class="source-card"><div><h3>${s.title}</h3><p>${s.text}<br>Producteur : ${s.producer} · ${s.date}</p><span class="source-status">Source officielle intégrée</span></div><a href="${s.url}" target="_blank" rel="noopener">Ouvrir ↗</a></article>`).join("")}
function search(){const q=document.getElementById("searchInput").value.trim().toLowerCase(),box=document.getElementById("searchResults");if(!q)return;const items=state.data.communes.features.filter(f=>f.properties.nom.toLowerCase().includes(q)).slice(0,7);box.innerHTML=items.length?items.map(f=>`<button data-code="${f.properties.code}">${f.properties.nom}</button>`).join(""):"<button>Aucun résultat dans le Val-d’Oise</button>";box.hidden=false;box.querySelectorAll("[data-code]").forEach(b=>b.onclick=()=>{const f=items.find(x=>x.properties.code===b.dataset.code);map.fitBounds(L.geoJSON(f).getBounds(),{padding:[40,40],maxZoom:13});openCommune(b.dataset.code);box.hidden=true})}
function makeCharts(){state.charts.forEach(c=>c.destroy());const all=Object.values(state.data.byCommune),years=[2020,2021,2022,2023,2024],series=years.map(y=>all.reduce((n,c)=>n+(c.cons[y]?.total||0),0)),latest=series.at(-1),prev=series[0],sectorKeys=[["Résidentiel","residentiel"],["Tertiaire","tertiaire"],["Industrie","industrie"],["Agriculture","agriculture"]],sector=sectorKeys.map(([,k])=>all.reduce((n,c)=>n+(c.cons[2024]?.[k]||0),0)),prod={};state.data.production.forEach(r=>prod[r.filiere||"Autre"]=(prod[r.filiere||"Autre"]||0)+(r.puissance_kw||0));const dpe={A:0,B:0,C:0,D:0,E:0,F:0,G:0};state.data.dpe.forEach(x=>Object.keys(dpe).forEach(k=>dpe[k]+=x.classes[k]||0));const dpeTotal=Object.values(dpe).reduce((a,b)=>a+b,0),pass=dpe.F+dpe.G,common={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom",labels:{boxWidth:11,font:{family:"Marianne"}}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:"#edf1f3"}}}};document.getElementById("dashboardKpis").innerHTML=[[`${fmt(latest/1e6,2)} TWh`,"consommation 2024","Électricité + gaz"],[`${fmt((latest-prev)/prev*100,1)} %`,"évolution depuis 2020","Agence ORE"],[`${fmt(all.reduce((n,c)=>n+c.power,0)/1000,1)} MW`,"puissance publiée","Installations en service"],[`${fmt(pass/dpeTotal*100,1)} %`,"DPE classés F ou G","Base ADEME"],[`${fmt(state.data.meta.dpeRows)}`,"DPE analysés","Agrégés par commune"],["183","communes couvertes","Référentiel 2026"]].map(([v,l,s])=>`<article><strong>${v}</strong><span>${l}</span><small>${s}</small></article>`).join("");state.charts.push(new Chart("consumptionChart",{type:"line",data:{labels:years,datasets:[{label:"Consommation (MWh)",data:series,borderColor:"#000091",backgroundColor:"#00009122",fill:true,tension:.2}]},options:common}));state.charts.push(new Chart("sectorChart",{type:"doughnut",data:{labels:sectorKeys.map(x=>x[0]),datasets:[{data:sector,backgroundColor:["#009081","#00a7b5","#e1000f","#f49b2f"]}]},options:{responsive:true,maintainAspectRatio:false,plugins:common.plugins}}));state.charts.push(new Chart("productionChart",{type:"bar",data:{labels:Object.keys(prod),datasets:[{data:Object.values(prod),backgroundColor:"#18753c",borderRadius:5}]},options:common}));state.charts.push(new Chart("dpeChart",{type:"bar",data:{labels:Object.keys(dpe),datasets:[{label:"Diagnostics",data:Object.values(dpe),backgroundColor:["#319834","#56ae35","#c8d300","#f4e70f","#f0b50f","#e97720","#d7221f"],borderRadius:4}]},options:common}));document.getElementById("insightValue").textContent=`${fmt(pass/dpeTotal*100,1)} %`;document.getElementById("insightText").textContent=`des DPE enregistrés sont classés F ou G. La base recense ${fmt(dpeTotal)} diagnostics valides dans le Val-d’Oise.`}
async function init(){renderLayers();renderSources();const [communes,consumption,production,dpe,meta]=await Promise.all(["communes.geojson","consommation.json","production.json","dpe.json","meta.json"].map(f=>fetch(`data/${f}`).then(r=>{if(!r.ok)throw Error(f);return r.json()})));state.data={communes,consumption,production,dpe,meta};prepare();prepareEnergy();territoryMask(communes);setLayer(layers[0],true);document.getElementById("mapStatus").textContent=`12 lectures cartographiques prêtes · ${meta.dpeRows.toLocaleString("fr-FR")} DPE agrégés`}
document.getElementById("searchButton").onclick=search;document.getElementById("searchInput").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();search()}};document.getElementById("resetView").onclick=()=>state.territory?map.fitBounds(state.territory.getBounds(),{padding:[38,38]}):map.fitBounds(BOUNDS_95);document.getElementById("resetPanel").onclick=()=>document.getElementById("resetView").click();document.getElementById("closeDetail").onclick=()=>document.getElementById("detailPanel").classList.remove("open");document.getElementById("clearLayers").onclick=()=>{clearActive("");state.active=null;renderEmptyLegend()};document.getElementById("openSources").onclick=()=>document.getElementById("sourcesDialog").showModal();document.getElementById("openDashboard").onclick=()=>{makeCharts();document.getElementById("dashboardDialog").showModal()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());document.querySelectorAll("[data-basemap]").forEach(b=>b.onclick=()=>{const id=b.dataset.basemap;if(id===state.basemap)return;map.removeLayer(baseLayers[state.basemap]);baseLayers[id].addTo(map);baseLayers[id].bringToBack();state.basemap=id;document.querySelectorAll("[data-basemap]").forEach(x=>x.classList.toggle("active",x===b))});const mobile=document.getElementById("mobileLayers"),sidebar=document.getElementById("layerSidebar");mobile.onclick=()=>{const open=sidebar.classList.toggle("open");mobile.setAttribute("aria-expanded",open);mobile.textContent=open?"Fermer":"Données"};init().catch(e=>{console.error(e);document.getElementById("mapStatus").textContent="Impossible de charger les données territoriales"});
